<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/assuredworkloads/v1beta1/assuredworkloads.proto

namespace Google\Cloud\AssuredWorkloads\V1beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request to check if source workload can be moved to target workload.
 *
 * Generated from protobuf message <code>google.cloud.assuredworkloads.v1beta1.AnalyzeWorkloadMoveRequest</code>
 */
class AnalyzeWorkloadMoveRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Required. The resource name of the Workload to fetch. This is the workloads's
     * relative path in the API, formatted as
     * "organizations/{organization_id}/locations/{location_id}/workloads/{workload_id}".
     * For example,
     * "organizations/123/locations/us-east1/workloads/assured-workload-2".
     *
     * Generated from protobuf field <code>string target = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $target = '';
    protected $projectOrWorkloadResource;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $source
     *           The Source is project based Workload to be moved. This is the workloads's
     *           relative path in the API, formatted as
     *           "organizations/{organization_id}/locations/{location_id}/workloads/{workload_id}".
     *           For example,
     *           "organizations/123/locations/us-east1/workloads/assured-workload-1".
     *     @type string $project
     *           The Source is a project based to be moved.
     *           This is the project's relative path in the API, formatted as
     *           "cloudresourcemanager.googleapis.com/projects/{project_number}"
     *           "projects/{project_number}"
     *           "cloudresourcemanager.googleapis.com/projects/{project_id}"
     *           "projects/{project_id}"
     *           For example,
     *           "organizations/123/locations/us-east1/workloads/assured-workload-1".
     *     @type string $target
     *           Required. The resource name of the Workload to fetch. This is the workloads's
     *           relative path in the API, formatted as
     *           "organizations/{organization_id}/locations/{location_id}/workloads/{workload_id}".
     *           For example,
     *           "organizations/123/locations/us-east1/workloads/assured-workload-2".
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Assuredworkloads\V1Beta1\Assuredworkloads::initOnce();
        parent::__construct($data);
    }

    /**
     * The Source is project based Workload to be moved. This is the workloads's
     * relative path in the API, formatted as
     * "organizations/{organization_id}/locations/{location_id}/workloads/{workload_id}".
     * For example,
     * "organizations/123/locations/us-east1/workloads/assured-workload-1".
     *
     * Generated from protobuf field <code>string source = 1;</code>
     * @return string
     */
    public function getSource()
    {
        return $this->readOneof(1);
    }

    public function hasSource()
    {
        return $this->hasOneof(1);
    }

    /**
     * The Source is project based Workload to be moved. This is the workloads's
     * relative path in the API, formatted as
     * "organizations/{organization_id}/locations/{location_id}/workloads/{workload_id}".
     * For example,
     * "organizations/123/locations/us-east1/workloads/assured-workload-1".
     *
     * Generated from protobuf field <code>string source = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSource($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * The Source is a project based to be moved.
     * This is the project's relative path in the API, formatted as
     * "cloudresourcemanager.googleapis.com/projects/{project_number}"
     * "projects/{project_number}"
     * "cloudresourcemanager.googleapis.com/projects/{project_id}"
     * "projects/{project_id}"
     * For example,
     * "organizations/123/locations/us-east1/workloads/assured-workload-1".
     *
     * Generated from protobuf field <code>string project = 3;</code>
     * @return string
     */
    public function getProject()
    {
        return $this->readOneof(3);
    }

    public function hasProject()
    {
        return $this->hasOneof(3);
    }

    /**
     * The Source is a project based to be moved.
     * This is the project's relative path in the API, formatted as
     * "cloudresourcemanager.googleapis.com/projects/{project_number}"
     * "projects/{project_number}"
     * "cloudresourcemanager.googleapis.com/projects/{project_id}"
     * "projects/{project_id}"
     * For example,
     * "organizations/123/locations/us-east1/workloads/assured-workload-1".
     *
     * Generated from protobuf field <code>string project = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setProject($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Required. The resource name of the Workload to fetch. This is the workloads's
     * relative path in the API, formatted as
     * "organizations/{organization_id}/locations/{location_id}/workloads/{workload_id}".
     * For example,
     * "organizations/123/locations/us-east1/workloads/assured-workload-2".
     *
     * Generated from protobuf field <code>string target = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return string
     */
    public function getTarget()
    {
        return $this->target;
    }

    /**
     * Required. The resource name of the Workload to fetch. This is the workloads's
     * relative path in the API, formatted as
     * "organizations/{organization_id}/locations/{location_id}/workloads/{workload_id}".
     * For example,
     * "organizations/123/locations/us-east1/workloads/assured-workload-2".
     *
     * Generated from protobuf field <code>string target = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param string $var
     * @return $this
     */
    public function setTarget($var)
    {
        GPBUtil::checkString($var, True);
        $this->target = $var;

        return $this;
    }

    /**
     * @return string
     */
    public function getProjectOrWorkloadResource()
    {
        return $this->whichOneof("projectOrWorkloadResource");
    }

}

