<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/assuredworkloads/v1beta1/assuredworkloads.proto

namespace Google\Cloud\AssuredWorkloads\V1beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Response with the analysis if the source workload can be moved to the target
 * workload
 *
 * Generated from protobuf message <code>google.cloud.assuredworkloads.v1beta1.AnalyzeWorkloadMoveResponse</code>
 */
class AnalyzeWorkloadMoveResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * List of blockers that prevent moving the source workload to the target
     * workload
     *
     * Generated from protobuf field <code>repeated string blockers = 1;</code>
     */
    private $blockers;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $blockers
     *           List of blockers that prevent moving the source workload to the target
     *           workload
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Assuredworkloads\V1Beta1\Assuredworkloads::initOnce();
        parent::__construct($data);
    }

    /**
     * List of blockers that prevent moving the source workload to the target
     * workload
     *
     * Generated from protobuf field <code>repeated string blockers = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBlockers()
    {
        return $this->blockers;
    }

    /**
     * List of blockers that prevent moving the source workload to the target
     * workload
     *
     * Generated from protobuf field <code>repeated string blockers = 1;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBlockers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->blockers = $arr;

        return $this;
    }

}

