<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/assuredworkloads/v1beta1/assuredworkloads.proto

namespace Google\Cloud\AssuredWorkloads\V1beta1;

if (false) {
    /**
     * This class is deprecated. Use Google\Cloud\AssuredWorkloads\V1beta1\RestrictAllowedServicesRequest\RestrictionType instead.
     * @deprecated
     */
    class RestrictAllowedServicesRequest_RestrictionType {}
}
class_exists(RestrictAllowedServicesRequest\RestrictionType::class);
@trigger_error('Google\Cloud\AssuredWorkloads\V1beta1\RestrictAllowedServicesRequest_RestrictionType is deprecated and will be removed in a future release. Use Google\Cloud\AssuredWorkloads\V1beta1\RestrictAllowedServicesRequest\RestrictionType instead', E_USER_DEPRECATED);

